server:
  port: 8888

spring:
  application:
    name: frontend
  zipkin:
    base-url: http://127.0.0.1:9411
    kafka:
      topic: zipkin
  sleuth:
    sampler:
      percentage: 1.0
  kafka:
    bootstrap-servers: 127.0.0.1:9092

feign:
  hystrix:
    enabled: true

