server:
  port: 9000

spring:
  application:
    name: backend
  zipkin:
    base-url: http://127.0.0.1:9411
    kafka:
      topic: zipkin
  sleuth:
    sampler:
      percentage: 1.0
  #rabbitmq:
  #  host: localhost
  #  port: 5672
  #  #username: guest
  #  #password: guest
  #  queue: zipkin
  kafka:
    bootstrap-servers: 127.0.0.1:9092